namespace GitHubReviewApp.Services;

/// <summary>
/// Simulates Claude API responses for local testing without making real API calls.
/// Swap this with <see cref="ClaudeService"/> in Program.cs when testing the GitHub App end-to-end.
/// </summary>
public class MockClaudeService : IClaudeService
{
    private readonly ILogger<MockClaudeService> _logger;

    public MockClaudeService(ILogger<MockClaudeService> logger)
    {
        _logger = logger;
    }

    public async Task<string> ReviewDiffAsync(string prTitle, string diff)
    {
        _logger.LogWarning("MockClaudeService is active — no real API call will be made.");

        // Simulate network + inference latency
        await Task.Delay(TimeSpan.FromSeconds(1));

        var lineCount  = diff.Split('\n').Length;
        var addedLines = diff.Split('\n').Count(l => l.StartsWith('+') && !l.StartsWith("+++"));
        var removedLines = diff.Split('\n').Count(l => l.StartsWith('-') && !l.StartsWith("---"));

        return $"""
            ## Code Review — {prTitle}

            > **Note:** This review was generated by `MockClaudeService` and does not reflect a real Claude analysis.

            ### Summary

            The diff touches **{lineCount} lines** ({addedLines} added, {removedLines} removed). Overall the change looks structurally sound.

            ### Observations

            - **Correctness:** No obvious logic errors detected in this simulated review.
            - **Security:** No injection or authentication concerns identified (mock scan only).
            - **Performance:** Change appears localised; no broad performance concerns.
            - **Maintainability:** Code follows existing patterns in the repository.

            ### Suggestions

            1. Consider adding unit tests if this path isn't already covered.
            2. Verify error handling at any new system boundaries introduced by this change.

            ---
            _This is a **mock review**. Replace `MockClaudeService` with `ClaudeService` in `Program.cs` for real reviews._
            """;
    }
}
